import type { Project, ChromeWindowInfo } from '@/types';
import type { AdvancedTask } from '@/types/tasks';
import { nanoid } from 'nanoid';

const generateId = () => nanoid();

// Mock data for Chrome Windows and Tabs
export const mockChromeWindows: ChromeWindowInfo[] = [
  {
    id: 1,
    name: 'Work Projects',
    tabs: [
      {
        id: 101,
        title: 'Q3 Planning Doc - Google Docs',
        url: 'https://docs.google.com/document/d/example1',
        favIconUrl: 'https://www.google.com/s2/favicons?domain=docs.google.com',
        windowId: 1,
      },
      {
        id: 102,
        title: 'Competitor Analysis - Figma',
        url: 'https://www.figma.com/file/example2',
        favIconUrl: 'https://www.google.com/s2/favicons?domain=figma.com',
        windowId: 1,
      },
      {
        id: 103,
        title: 'Internal Dashboard',
        url: 'https://internal.example.com/dashboard',
        favIconUrl: 'https://www.google.com/s2/favicons?domain=example.com',
        windowId: 1,
      },
    ],
    isFocused: true,
  },
  {
    id: 2,
    name: 'Research & News',
    tabs: [
      {
        id: 201,
        title: 'Tech News Today - TechCrunch',
        url: 'https://techcrunch.com',
        favIconUrl: 'https://www.google.com/s2/favicons?domain=techcrunch.com',
        windowId: 2,
      },
      {
        id: 202,
        title: 'Next.js Official Docs',
        url: 'https://nextjs.org/docs',
        favIconUrl: 'https://www.google.com/s2/favicons?domain=nextjs.org',
        windowId: 2,
      },
    ],
  },
];

export const initialProjects: Project[] = [
  {
    id: generateId(),
    name: 'Work',
    description: 'Projects related to work tasks and responsibilities.',
    color: '#4285F4',
    icon: '💼',
    createdAt: new Date(),
    updatedAt: new Date(),
    bookmarkFolderId: undefined,
    collections: [
      {
        id: generateId(),
        name: 'Q3 Planning',
        description: 'Planning documents and resources for the third quarter.',
        links: [
          {
            id: generateId(),
            title: 'Project Brief',
            url: 'https://docs.example.com/brief',
            order: 0,
            createdAt: new Date(),
            favIconUrl:
              'https://www.google.com/s2/favicons?domain=docs.example.com',
            tags: ['planning', 'brief'],
            notes: 'Main project brief document.',
          },
          {
            id: generateId(),
            title: 'Roadmap',
            url: 'https://sheets.example.com/roadmap',
            order: 1,
            createdAt: new Date(),
            favIconUrl:
              'https://www.google.com/s2/favicons?domain=sheets.example.com',
            tags: ['planning', 'roadmap'],
            notes: 'Product and feature roadmap.',
          },
        ],
        minimized: false,
        order: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
        color: undefined,
      },
    ],
  },
  {
    id: generateId(),
    name: 'Personal',
    description: 'Personal projects, hobbies, and interests.',
    color: '#34A853',
    icon: '🏠',
    createdAt: new Date(),
    updatedAt: new Date(),
    bookmarkFolderId: undefined,
    collections: [
      {
        id: generateId(),
        name: 'Recipes',
        description: 'Collection of favorite recipes.',
        links: [
          {
            id: generateId(),
            title: 'Pasta Recipe',
            url: 'https://recipes.example.com/pasta',
            order: 0,
            createdAt: new Date(),
            favIconUrl:
              'https://www.google.com/s2/favicons?domain=recipes.example.com',
            tags: ['food', 'pasta'],
            notes: 'Delicious pasta recipe.',
          },
        ],
        minimized: false,
        order: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
        color: undefined,
      },
    ],
  },
];

// Sample tasks with due dates for testing calendar functionality
export const initialTasks: AdvancedTask[] = [
  {
    id: generateId(),
    title: 'Complete Q3 Planning Document',
    description:
      'Finalize the quarterly planning document with all team inputs',
    priority: 'high',
    status: 'in-progress',
    dueDate: new Date(2025, 5, 15), // June 15, 2025
    category: 'Planning',
    tags: ['planning', 'quarterly', 'documentation'],
    subtasks: [],
    attachments: [],
    notes: 'Need to gather input from all department heads',
    createdAt: new Date(2025, 5, 1),
    updatedAt: new Date(2025, 5, 10),
    reminders: [],
    progress: 60,
    comments: [],
    activities: [],
    isArchived: false,
    isFavorite: false,
    customFields: {},
  },
  {
    id: generateId(),
    title: 'Review Marketing Campaign',
    description: 'Review and approve the new marketing campaign materials',
    priority: 'medium',
    status: 'todo',
    dueDate: new Date(2025, 5, 20), // June 20, 2025
    category: 'Marketing',
    tags: ['marketing', 'review', 'campaign'],
    subtasks: [],
    attachments: [],
    notes: 'Focus on brand consistency and messaging',
    createdAt: new Date(2025, 5, 5),
    updatedAt: new Date(2025, 5, 5),
    reminders: [],
    progress: 0,
    comments: [],
    activities: [],
    isArchived: false,
    isFavorite: true,
    customFields: {},
  },
  {
    id: generateId(),
    title: 'Team Meeting Preparation',
    description: 'Prepare agenda and materials for the monthly team meeting',
    priority: 'medium',
    status: 'todo',
    dueDate: new Date(2025, 5, 12), // June 12, 2025
    category: 'Meetings',
    tags: ['meeting', 'preparation', 'team'],
    subtasks: [],
    attachments: [],
    notes: 'Include project updates and Q3 goals discussion',
    createdAt: new Date(2025, 5, 8),
    updatedAt: new Date(2025, 5, 8),
    reminders: [],
    progress: 25,
    comments: [],
    activities: [],
    isArchived: false,
    isFavorite: false,
    customFields: {},
  },
  {
    id: generateId(),
    title: 'Code Review - Feature Branch',
    description: 'Review the new feature implementation before merge',
    priority: 'urgent',
    status: 'todo',
    dueDate: new Date(2025, 5, 11), // June 11, 2025
    category: 'Development',
    tags: ['code-review', 'feature', 'urgent'],
    subtasks: [],
    attachments: [],
    notes: 'Check for security vulnerabilities and performance issues',
    createdAt: new Date(2025, 5, 10),
    updatedAt: new Date(2025, 5, 10),
    reminders: [],
    progress: 0,
    comments: [],
    activities: [],
    isArchived: false,
    isFavorite: false,
    customFields: {},
  },
  {
    id: generateId(),
    title: 'Update Documentation',
    description: 'Update API documentation with recent changes',
    priority: 'low',
    status: 'completed',
    dueDate: new Date(2025, 5, 8), // June 8, 2025
    completedAt: new Date(2025, 5, 7),
    category: 'Documentation',
    tags: ['documentation', 'api', 'maintenance'],
    subtasks: [],
    attachments: [],
    notes: 'All endpoints now properly documented',
    createdAt: new Date(2025, 5, 1),
    updatedAt: new Date(2025, 5, 7),
    reminders: [],
    progress: 100,
    comments: [],
    activities: [],
    isArchived: false,
    isFavorite: false,
    customFields: {},
  },
];
